ConsoleAppcore/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleAppcore.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admin")]
    //[Route("admin/[controller]/[action]")]
    public class HomeController : Controller
    {
        // GET: HomeController
         
        [Route("index")]
        public ActionResult Index()
        {
            return View();
        }

        // GET: HomeController/Details/5
        [Route("details/{id}")]
        public ActionResult Details(int id)
        {
            return View(id);
        }

        // GET: HomeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("create")]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [Route("edit")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomeController/Edit/5
        [HttpPost]
        [Route("edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HomeController/Delete/5
        [Route("delete")]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [Route("delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ConsoleAppcore/Components/TopBooksViewComponent.cs
using ConsoleAppcore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleAppcore.Components
{
    public class TopBooksViewComponent:ViewComponent
    {
        private readonly IBookRepository _bookRepository;
        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

     

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var books = await _bookRepository.GetTopBookAsync();
            return View(books);
        }

        
    }
}

ConsoleAppcore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using ConsoleAppcore.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using ConsoleAppcore.Repository;
using ConsoleAppcore.Services;
using System.Net.Mail;
using Microsoft.AspNetCore.Authorization;

namespace ConsoleAppcore.Controllers
{
        
    public class HomeController : Controller
    {
        private readonly NewBookAlertConfig _newBookAlterconfiguration;
        private readonly NewBookAlertConfig _thirdPartyBookconfiguration;
        private readonly IMessageRepository _messageRepository;
        private readonly IUserService _userService;
        private readonly IEmailService _emailService;

        public HomeController(IOptionsSnapshot<NewBookAlertConfig> newBookAlterconfiguration,
            IMessageRepository messageRepository,
             IUserService userService,
             IEmailService emailService)
        {
            _newBookAlterconfiguration = newBookAlterconfiguration.Get("Internal book");
            _thirdPartyBookconfiguration = newBookAlterconfiguration.Get("ThirdPartyBook");
            _messageRepository = messageRepository;
            _userService = userService;
            _emailService = emailService;
        }

        
       
        public ActionResult Index()
        {
            //UserEmailOptions options = new UserEmailOptions
            //{
            //    ToEmails = new List<string>() { "test@gmail.com" },
            //    PlaceHolders = new List<KeyValuePair<string, string>>()
            //    {
            //        new KeyValuePair<string, string>("{{UserName}}","Nitish")
            //    }
            //};
            // await _emailService.SendTestEmail(options);

            //  var userId = _userService.GetUserId();
            //var isLoggedIn = _userService.IsAuthenticated();
            //bool isDisplay = _newBookAlterconfiguration.DisplayNewBookAlert;
            //bool isDisplay1 = _thirdPartyBookconfiguration.DisplayNewBookAlert;
            //var value = _messageRepository.GetName();
            //var result = newbook.GetValue<bool>("DisplayNewBookAlert");
            //var bookname = newbook.GetValue<string>("BookName");
            //var result = configuration["AppName"];
            //var key1 = configuration["infoObj:key1"];
            //var key2 = configuration["infoObj:key2"];
            //var key3 = configuration["infoObj:key3:key3obj1"];
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        [Authorize(Roles ="Admin")]
        public ActionResult ContactUs()
        {
            return View();
        }

    }
}

ConsoleAppcore/Views/Home/AboutUs.cshtml
<h1> This is AboutUs</h1>
@section breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">page1</a></li>
            <li class="breadcrumb-item active" aria-current="page">AboutUs</li>


        </ol>
    </nav>
}

ConsoleAppcore/Views/Home/ContactUs.cshtml
<h2> This is ContactUs page</h2>
@section breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">page1</a></li>
            <li class="breadcrumb-item active" aria-current="page">ContactUs</li>


        </ol>
    </nav>
}

ConsoleAppcore/Views/Home/Index.cshtml
@inject ConsoleAppcore.Repository.IBookRepository _bookRepository

<section class=" jumbotron text-center">
    <div class="container">
        <h1>Welcome to book strore </h1>
       
        <p class="lead text-muted">

            Hii this is the home page
        </p>
        <p>
            <a href="#" class="btn btn-primary m-2">Search Books</a>
        </p>
        @foreach(var item in await _bookRepository.GetAllBooks())
            {
                <h2>@item.Title</h2>
            }
    </div>
</section>
@section breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">page1</a></li>
            <li class="breadcrumb-item active" aria-current="page">Index</li>


        </ol>
    </nav>
}
@await Component.InvokeAsync("TopBooks")
@*<vc:top-books></vc:top-books>*@
@section scripts{
    <script>
        $(document).ready(function () {
            alert("documnet is ready");;
        })
    </script>
}